# Generated by Django 4.1.4 on 2022-12-10 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Beginner', 'Beginner'), ('Pre-intermediate', 'Pre-intermediate'), (
                    'Intermediate', 'Intermediate'), ('Upper-intermediate', 'Upper-intermediate')], max_length=255, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Куратор',
                'verbose_name_plural': 'Кураторы',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), (
                    'Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Восресенье', 'Восресенье')], max_length=255, verbose_name='День недели')),
                ('time', models.DateField(verbose_name='Время начала занятия')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='speaking_clubs.level', verbose_name='Уровень')),
                ('teachers', models.ManyToManyField(
                    to='speaking_clubs.teacher', verbose_name='Кураторы')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.URLField(verbose_name='Ссылка на чат')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='speaking_clubs.group', verbose_name='Группа')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='speaking_clubs.teacher', verbose_name='Куратор')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
    ]
