# Generated by Django 2.2.27 on 2022-12-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_clubs', '0003_chat_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='weekday',
        ),
        migrations.AddField(
            model_name='group',
            name='weekdays',
            field=models.CharField(choices=[('Понедельник - Среда - Пятница', 'Понедельник - Среда - Пятница'), ('Вторник - Четверг - Суббота', 'Вторник - Четверг - Суббота')], default='Понедельник - Среда - Пятница', max_length=255, verbose_name='День недели'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='level',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
