# Generated by Django 2.2.27 on 2022-12-25 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('speaking_clubs', '0004_auto_20221219_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=255, verbose_name='Период')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Пакет',
                'verbose_name_plural': 'Пакеты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.PositiveIntegerField(verbose_name='Номер закза')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл. почта')),
                ('time', models.TimeField(verbose_name='Время начала занятия')),
                ('weekdays', models.CharField(choices=[('Понедельник - Среда - Пятница', 'Понедельник - Среда - Пятница'), ('Вторник - Четверг - Суббота', 'Вторник - Четверг - Суббота')], max_length=255, verbose_name='Дни недели')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='speaking_clubs.Offer', verbose_name='Пакет')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
