# Generated by Django 2.2.27 on 2022-12-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_clubs', '0005_offer_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
