# Generated by Django 2.2.27 on 2022-12-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_clubs', '0006_auto_20221225_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='a', max_length=255, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
