# Generated by Django 2.2.27 on 2022-12-25 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_clubs', '0007_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speaking_clubs.Offer', verbose_name='Пакет'),
        ),
    ]
