# Generated by Django 2.2.27 on 2022-12-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_clubs', '0009_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='test',
            field=models.TextField(default={'nav-Grammar': [0, 0, 34], 'nav-Listening': [0, 0, 15], 'nav-Reading': [0, 0, 16], 'nav-Vocabulary': [0, 0, 20], 'nav-Writing': [0, 0, 16]}, verbose_name='Результаты тестов'),
        ),
    ]
