# Generated by Django 2.2.27 on 2022-12-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_clubs', '0010_student_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='chat', to='speaking_clubs.Student', verbose_name='Ученики'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2')], max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='test',
            field=models.TextField(default={'nav-Grammar': [], 'nav-Listening': [], 'nav-Reading': [], 'nav-Vocabulary': [], 'nav-Writing': []}, verbose_name='Результаты тестов'),
        ),
    ]
