# Generated by Django 2.2.27 on 2023-08-19 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Уровень')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gc_user', models.IntegerField(verbose_name='ID с GetCourse')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('photo', models.ImageField(upload_to='individual_lessons/img/teacher_photo', verbose_name='Фото профиля')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individual_lessons.IndividualLevel', verbose_name='Уровень')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gc_user', models.IntegerField(verbose_name='ID с GetCourse')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('hours_paid', models.FloatField(default=0, verbose_name='Часов оплачено')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='individual_lessons.IndividualLevel', verbose_name='Уровень')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='individual_lessons.IndividualTeacher', verbose_name='Преподаватель')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='individual_lessons.IndividualStudent', verbose_name='Ученик')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='individual_lessons.IndividualTeacher', verbose_name='Преподаватель')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='individual_lessons.IndividualTopic', verbose_name='Тема')),
            ],
        ),
    ]
