# Generated by Django 2.2.27 on 2023-09-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_lessons', '0002_auto_20230906_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='individuallesson',
            name='status',
            field=models.CharField(choices=[('Создан', 'Создан'), ('Почти отменен', 'Почти отменен'), ('Забронирован', 'Забронирован')], default='Создан', max_length=255, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='individualteacher',
            name='zoom_email',
            field=models.EmailField(default='', max_length=254, verbose_name='Почта Zoom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualteacher',
            name='zoom_key',
            field=models.CharField(default='', max_length=500, verbose_name='Ключ Zoom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualteacher',
            name='zoom_sec',
            field=models.CharField(default='', max_length=500, verbose_name='Секретный ключ Zoom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individualstudent',
            name='hours_paid',
            field=models.PositiveIntegerField(default=0, verbose_name='Занятий оплачено'),
        ),
    ]
