# Generated by Django 2.2.27 on 2023-09-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_lessons', '0003_auto_20230909_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='individuallesson',
            name='zoom_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID встречи'),
        ),
        migrations.AddField(
            model_name='individuallesson',
            name='zoom_password',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Пароль встречи'),
        ),
        migrations.AddField(
            model_name='individuallesson',
            name='zoom_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на встречу'),
        ),
    ]
