# Generated by Django 2.2.27 on 2023-09-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_lessons', '0004_auto_20230909_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualteacher',
            name='zoom_email',
        ),
        migrations.AddField(
            model_name='individualteacher',
            name='zoom_client',
            field=models.CharField(default='', max_length=500, verbose_name='Client ID Zoom'),
            preserve_default=False,
        ),
    ]
