# Generated by Django 2.2.27 on 2023-03-06 19:58


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_clubs', '0003_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='test',
            field=models.JSONField(blank=True, null=True, verbose_name='Результаты тестов'),
        ),
    ]
