# Generated by Django 2.2.27 on 2023-09-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_clubs', '0018_student_is_done_by_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergc',
            name='user_id',
            field=models.CharField(default='', max_length=255, verbose_name='ID c GetCourse'),
            preserve_default=False,
        ),
    ]
