# Generated by Django 2.2.27 on 2023-09-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_clubs', '0019_ordergc_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_number',
            field=models.PositiveIntegerField(verbose_name='Номер заказа'),
        ),
    ]
