# Generated by Django 2.2.27 on 2023-11-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_clubs', '0021_auto_20230919_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='weekdays',
            field=models.CharField(choices=[('Понедельник - Пятница', 'Понедельник - Пятница'), ('Среда - Суббота', 'Среда - Суббота'), ('Понедельник - Суббота', 'Понедельник - Суббота'), ('Понедельник - Четверг', 'Понедельник - Четверг')], max_length=255, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='order',
            name='weekdays',
            field=models.CharField(blank=True, choices=[('Понедельник - Пятница', 'Понедельник - Пятница'), ('Среда - Суббота', 'Среда - Суббота'), ('Понедельник - Суббота', 'Понедельник - Суббота'), ('Понедельник - Четверг', 'Понедельник - Четверг')], max_length=255, null=True, verbose_name='Дни недели'),
        ),
    ]
