# Generated by Django 2.2.27 on 2024-02-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_clubs', '0023_auto_20231207_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='weekdays',
            field=models.CharField(choices=[('Понедельник - Пятница', 'Понедельник - Пятница'), ('Среда - Суббота', 'Среда - Суббота'), ('Понедельник - Суббота', 'Понедельник - Суббота'), ('Понедельник - Четверг', 'Понедельник - Четверг'), ('Вторник - Воскресенье', 'Вторник - Воскресенье'), ('Вторник - Пятница', 'Вторник - Пятница'), ('Вторник - Четверг', 'Вторник - Четверг')], max_length=255, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='order',
            name='weekdays',
            field=models.CharField(blank=True, choices=[('Понедельник - Пятница', 'Понедельник - Пятница'), ('Среда - Суббота', 'Среда - Суббота'), ('Понедельник - Суббота', 'Понедельник - Суббота'), ('Понедельник - Четверг', 'Понедельник - Четверг'), ('Вторник - Воскресенье', 'Вторник - Воскресенье'), ('Вторник - Пятница', 'Вторник - Пятница'), ('Вторник - Четверг', 'Вторник - Четверг')], max_length=255, null=True, verbose_name='Дни недели'),
        ),
    ]
