# Generated by Django 2.2.27 on 2025-06-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_clubs', '0025_auto_20240516_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='finished_test_1',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время завершения 1 теста'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_test_2',
            field=models.BooleanField(default=False, verbose_name='Перешел к тесту 2'),
        ),
    ]
