# Generated by Django 4.1.4 on 2022-12-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.RemoveField(
            model_name='group',
            name='teachers',
        ),
        migrations.AddField(
            model_name='teacher',
            name='groups',
            field=models.ManyToManyField(
                to='speaking_clubs.group', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='time',
            field=models.TimeField(verbose_name='Время начала занятия'),
        ),
    ]
