# Generated by Django 4.1.4 on 2022-12-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_clubs', '0002_alter_chat_options_remove_group_teachers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='students',
            field=models.ManyToManyField(
                to='speaking_clubs.student', verbose_name='Ученики'),
        ),
    ]
